### PR TITLE
Rework of data parsing

### PR DESCRIPTION
**Pull request by FakeMichau**
Loving the project so far so I've decided to contribute. 
My work is far from finished but I would like to know your opinion.
I would like to complete the full parser, from simple name to inventory and skills.

### CODE REVIEW

**Comment by byt3m** [comment]
The character parser is awesome! How did you find out all that info about the .FCH file? Right now I use patterns like searching for beard and hair but you seem to know the format pretty well.

I closed your request because I will be uploading a new version and I had to recode some parts. I will re-open it just in case.

Will you be so glad of adding the parser after I upload the new version?

**Comment by FakeMichau** [comment]
I'm reverse engineering how the game reads saves and as the game is written in Unity it isn't that hard. 
Many things had to be changed and I still don't know how to deal with skin and hair color. You've made a nice preset, game gives you two sliders (one for skin) but the save itself holds 3 values for each. 
Maybe we could allow for weird color that are normally obtainable. More tests are needed.

I'm thinking It would be nice to have a Basic mode and an Advanced mode. In Basic there would be presets, more restrictions, no inventory editing but in Advanced everything would be allowed. 

I will just push what I've got for now and we will see what I have need to change.

**Comment by byt3m** [comment]
I just reverse engineered statically the FCH file. Tried it dynamically with x64dbg following the Kernel32 ReadFile function but I did not see it clearly and just stopped at that point. Where can I learn more about Unity in this matter? Is there maybe a program or something you used, or did you just follow the instructions in x64dbg/ollydbg or other disassembler?

Also, thanks a lot for your help this will make this program pretty awesome.

I will accept this pull request and as soon as I finish v1.4 we can start adding the inventory editor, basic/advance modes, etc.

**Comment by FakeMichau** [comment]
There is still need to combine that new parser with already existing code. That's why I still left that pr as a draft. I didn't test that code much and there's still some dubugging stuff. But you probably can manage.

I'm still open for helping with the app but as you've said I will wait for 1.4.
The code became quite messy. Parser could probably be seperated, or at least parts of it. Memory usage is also quite high. The basic idea is there but it needs more work. 
I'm kinda new to C# so there will be some bad code here and there but I hope I won't make your eyes bleed. 

I've used dnSpy. Replacing few files in the game file and you can attach dnSpy to the game and debug it, but that wasn't required here as you can simply look at the assembly_valheim.dll

**Comment by byt3m** [comment]
I uploaded what I did so far, dont want to add more functions as we will be using your parser. I will start working on the basic/advance modes while you add the parser and so on.

**Comment by FakeMichau** [comment]
Ok so I will make my changes again. Should I make a pr into main or 1.4 branch? 
With such a big changes it doesn't seem like a bad idea to have a temporary branch for implementing them and testing. 
Also if you want we could discuss ideas via Discord or something instead of here, FakeMichau#4936

**Comment by byt3m** [comment]
Lets work in the 1.4 branch until we release this version with the parser working on reading and writting the current info correctly (beard, hair and name). After, we can start making the inventory editor and so on.

I think it will be better to keep the customization class as it is. Like making a new file called "GameClasses" and add in it the reverse engineered classes (world, player, item, etc.). This way we can keep things separated and clear.

Lets continue this on discord, I will send you a friend request.

**Pull request merged**
